# Site settings
title: Dave Screwing Around
email: davemen@hotmail.com
# description: 
baseurl: "/case-studies" # the subpath of your site, e.g. /blog/
url: http://davemen.github.io" # the base hostname & protocol for your site
twitter_username: davemen
github_username:  davemen
encoding: utf-8

# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap